Repository miraisolutions/OasisUI, pull requests merged in 2018-09, with the labels that each got.

#64 Workflow restructuring
  BFE_RShiny/flamingo/NAMESPACE
  BFE_RShiny/flamingo/R/browse_server.R
  BFE_RShiny/flamingo/R/flamingoServer.R
  BFE_RShiny/flamingo/R/programmeDefinitionSingle_server.R
  BFE_RShiny/flamingo/R/programmeDefinitionSingle_ui.R
  BFE_RShiny/flamingo/inst/app/server.R
  BFE_RShiny/flamingo/man/accountDefinition.Rd
  BFE_RShiny/flamingo/man/executeDbQuery.Rd
  BFE_RShiny/flamingo/man/landingPage.Rd
  BFE_RShiny/flamingo/man/landingPageButtonUpdate.Rd
  BFE_RShiny/flamingo/man/loadProgrammeData.Rd
  BFE_RShiny/flamingo/man/loadProgrammeModel.Rd
  BFE_RShiny/flamingo/man/loginDialog.Rd
  BFE_RShiny/flamingo/man/modelSupplierPage.Rd
  BFE_RShiny/flamingo/man/pageheader.Rd
  BFE_RShiny/flamingo/man/pagestructure.Rd
  BFE_RShiny/flamingo/man/panelOutputModule.Rd
  BFE_RShiny/flamingo/man/panelSummaryTableModule.Rd
  BFE_RShiny/flamingo/man/reactiveNavigation.Rd
  BFE_RShiny/flamingo/man/showNotification.Rd
  BFE_RShiny/flamingo/man/visualizationBBR.Rd
Labels: bug, enhancement, reporting, workflowRedesign

#66 Workflow restructuring
  BFE_RShiny/flamingo/R/browse_server.R
  BFE_RShiny/flamingo/R/browse_ui.R
  BFE_RShiny/flamingo/R/programmeDefinitionSingle_server.R
  BFE_RShiny/flamingo/R/programmeDefinitionSingle_ui.R
Labels: bug, reporting, workflowRedesign

#67 Workflow restructuring
  BFE_RShiny/flamingo/NAMESPACE
  BFE_RShiny/flamingo/R/browse_server.R
  BFE_RShiny/flamingo/R/programmeDefinitionSingle_server.R
Labels: bug, reporting, workflowRedesign

#78 bsModal and bsButton changed to reduce dependency on shinyBS
  BFE_RShiny/flamingo/NAMESPACE
  BFE_RShiny/flamingo/R/defineAccount_server.R
  BFE_RShiny/flamingo/R/defineAccount_ui.R
  BFE_RShiny/flamingo/R/defineCompany_server.R
  BFE_RShiny/flamingo/R/defineCompany_ui.R
  BFE_RShiny/flamingo/R/defineUserAdmin_server.R
  BFE_RShiny/flamingo/R/defineUserAdmin_ui.R
  BFE_RShiny/flamingo/R/flamingoDB.R
  BFE_RShiny/flamingo/R/landingPage_server.R
  BFE_RShiny/flamingo/R/landingPage_ui.R
  BFE_RShiny/flamingo/R/model_server.R
  BFE_RShiny/flamingo/R/model_ui.R
  BFE_RShiny/flamingo/R/pagestructureSidebar.R
  BFE_RShiny/flamingo/R/programmeDefinitionSingle_server.R
  BFE_RShiny/flamingo/R/programmeDefinitionSingle_ui.R
  BFE_RShiny/flamingo/inst/app/www/css/flamingo-tweaks.css
  BFE_RShiny/flamingo/man/sidebar_button.Rd
Labels: maintenance
